
[config]
additional_profiles = [
    "ci-coverage-tasks",
    "ci-all-build-tasks",
    "ci-static-code-analysis-tasks",
    "publish-pre-cleanup"
]

[tasks.outdated]
force = true

[tasks.start-redis]
script = [
  "echo \"Starting Redis\"",
  "redis-server --loglevel warning &",
  "sleep 1"
]

[tasks.stop-redis]
script = [
  "echo \"Stopping any running Redis\"",
  "ps -ef | grep [r]edis-server | awk '{print $2}' | xargs kill -9 || true",
]

[tasks.pre-local-flow]
condition = { env_false = [ 'CARGO_MAKE_CI' ] }
run_task = "start-redis"

[tasks.post-local-flow]
condition = { env_false = [ 'CARGO_MAKE_CI' ] }
run_task = "stop-redis"

[tasks.pre-test]
alias = "pre-local-flow"

[tasks.post-test]
alias = "post-local-flow"

