
[config]
additional_profiles = [
    "ci-coverage-tasks",
    "ci-all-build-tasks",
    "ci-static-code-analysis-tasks",
    "publish-pre-cleanup"
#    "none-thread-safe-test"
]

[tasks.outdated]
force = true

[tasks.start-redis]
script = [
  "echo \"Starting Redis\"",
  "redis-server --loglevel warning &",
  "sleep 1"
]

[tasks.stop-redis]
script = [
  "echo \"Stopping any running Redis\"",
  "ps -ef | grep [r]edis-server | awk '{print $2}' | xargs kill -9 || true",
]

[tasks.init-build-flow]
dependencies = [
  "stop-redis",
  "start-redis"
]

[tasks.end-build-flow]
alias = "stop-redis"
