name: CI
on: [push, pull_request]
env:
  CLICOLOR_FORCE: 1
jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]
        os: [ubuntu-latest, macOS-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
    - name: Install cargo-make
      run: cargo install --debug cargo-make
    - name: Startup Redis
      uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: '5.x'
    - name: Run CI
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: cargo make ci-flow
